### ISSUE TITLE
Retroactive /trax stop hh:mm stops in the future

### ISSUE THREAD

**Issue by thebao** [EliotBerriot/trax#13]
After invoking `/trax stop 17h15` on a running task at day+1 the task completely disappears from the `/trax stats` table

```
Timers were successfully stopped on Jan. 6, 2017, 5:15 p.m.:
reticulating splines
```

**Comment by EliotBerriot** [comment]
I've thought about that, it's actually a feature, not a bug: if you now that you will work until a certain hour, you can stop the timer in advance.

However, a timer with an end date in the future but starting today should still appear in your reports, so i'll leave this issue open until it is fixed.
