### ISSUE TITLE
configure dateparser to prefer future dates

### ISSUE THREAD

**Issue by thperret** [EliotBerriot/trax#15]
When you add a reminder, you always want it in the future. In the [`parse_future` function](https://github.com/EliotBerriot/trax/blob/536473c969cefe388e601d4d20a0a3135e276bbf/trax/trax/utils.py#L21), the [default `PREFER_DATES_FROM`](https://github.com/scrapinghub/dateparser#incomplete-dates) settings is applied and choose past dates.

e.g.: if the current day is tuesday and you add a reminder for wednesday 10 o'clock, it will raise an error since the `parse_future` function won't return anything.

The easy fix is to specify `settings={'PREFER_DATES_FROM': 'future'}` in the parameters of the `dateparser.parse` function:
parse(u'wednesday 10h00', settings={'PREFER_DATES_FROM': 'future'})

**Comment by EliotBerriot** [comment]
I did'nt know they were settings for dateparser....

`/trax remind add "RTFM" "forever"`
