### ISSUE TITLE
Install without docker

### ISSUE THREAD

**Issue by hanzei** [EliotBerriot/trax#22]
I'm running mattermost on a shared system without docker. So I would love a way to install trax without docker.

**Comment by EliotBerriot** [comment]
I guess that, sooner or later this day had to com ;).

The good news is that Docker, Dockerfiles and docker-compose.yml file are de facto documenting most of the deployment and project architecture. I understand that a real documentation is needed though, and I'll start to work on it.

Basically, you will need to take all the services described in `docker-compose.yml`and make them available on your system. You'll need:

- A PostgreSQL server (you can use a shared one and even a remote one if you want)
- A Redis server (same here)
- A process manager, such as supervisor or systemd to run:
  1. The application server
  2. The application worker
- A webserver on your system with a reverse proxy configuration to talk to the application

To install the application dependencies, you would have to follow the [Dockerfile](https://github.com/EliotBerriot/trax/blob/master/compose/django/Dockerfile) steps, with few adjustements to make this more suitable on a shared system:

- use a python virtualenv
- move everything under a specific directory, such as `/srv/trax`

I'm only familiar with debian-based systems, so I'll start working on a documentation for those systems., but it should work similarly on most linux distros.

**Comment by EliotBerriot** [comment]
Okay I've opened #23 which is a first attempt at such a documentation. Please get back to me when you have reviewed this :)

**Comment by hanzei** [comment]
Fixed with https://github.com/EliotBerriot/trax/pull/23
