### ISSUE TITLE
Trax/django produces HTTP 500 internal server errors

### ISSUE THREAD

**Issue by christianlupus** [EliotBerriot/trax#25]
I tried to make trax running using docker. I went with your [suggestion ](https://traxio.readthedocs.io/en/latest/deploy.html)

    # clone the repository
    git clone https://github.com/EliotBerriot/trax.git
    cd trax
    
    # setup the environment variables
    # edit the .env file, especially the TIME_ZONE variable
    # and the DJANGO_ALLOWED_HOSTS one
    cp env.example .env
    nano .env
    
    # set up the docker-compose file
    # customize any configuration in the docker compose file
    # especially, you can change the listening port and ip
    cp docker-compose.example.yml docker-compose.yml
    nano docker-compose.yml
    
    # build and run the containers
    docker-compose build
    docker-compose up -d
    
    # create tables in the database
    docker-compose run django python manage.py migrate
    
    # create an admin user (this will be needed to configure your tokens)
    docker-compose run django python manage.py createsuperuser

Unfortunately you do not mention what the various settings mean and how they should be set up correctly.

I put an apache web server (serves also other sites) as a reverse proxy between the internet and trax. That is it is configured to forward all traffic for domain `trax.example.com` to the nginx in the docker container. I put in the list of allowed hosts the site `trax.example.com` as sole entry. Using this setup, I can connect to the django server (later I want to get rid of nginx but this is another story).

When I try to log in using my username and password as set up in the commands above, I get a HTTP error `500 Internal server error`. This is coming from django itself. I sniffed into the traffic of the bridge and the nginx sends the `POST` request to `/accounts/login` with the credentials to django. The result is the error 500.

In the docker logs there is nothing that looks suspicious except for some warnings about missing `.env` files. Especially there are no errors shown.

What can I do to track this further down?

**Comment by christianlupus** [comment]
Oh, by the way. My modifications:

    # diff env.example .env
    7c7
    < DJANGO_ADMIN_URL=
    ---
    > DJANGO_ADMIN_URL=^admin/
    14c14,15
    < DJANGO_ALLOWED_HOSTS=.trax.io
    ---
    > #DJANGO_ALLOWED_HOSTS=.trax.io
    > DJANGO_ALLOWED_HOSTS=trax.example.com
    35c36
    < TIME_ZONE=UTC
    ---
    > TIME_ZONE=Europe/Berlin
    
    # diff docker-compose.*
    36c36
    <       - "0.0.0.0:8079:80"
    ---
    >       - "127.0.0.1:8001:80"

**Comment by EliotBerriot** [comment]
Hi @christianlupus! Inside the `DJANGO_ALLOWED_HOSTS=` variable, you should put the domain name used to access your trax instance (`trax.example.com` seems invalid in this case).

Can you try that, reload the process and let me know if it works?

**Comment by christianlupus** [comment]
I replaced my real domain name with `example.com` throughout all my comments. I wanted to avoid putting a semi-installed installation of trax publicly on the web while sharing the url to it. Is it save to do so and there are no preconfigured user accounts?

By reloading you mean `docker-compose restart` or `down` and `up -d` or even `build`?

**Comment by christianlupus** [comment]
OK, I am ok with both. The url is https://trax.christian-wolf.click. I will add the `.env` file here as an [attachment `.env`](https://github.com/EliotBerriot/trax/files/2249382/env.txt).

**Comment by EliotBerriot** [comment]
Alright, I see nothing wrong with your env file. Without any log, it's hard to debug. You don't have anything at all in `docker-compose logs django` ?

**Comment by christianlupus** [comment]
Yes, there is quite something. I will attach the output of your command: [django.log](https://github.com/EliotBerriot/trax/files/2249426/django.log) or without the color scripts [django_clean.log](https://github.com/EliotBerriot/trax/files/2249434/django_clean.log).

**Comment by EliotBerriot** [comment]
And no new logs when you are logging in?

**Comment by christianlupus** [comment]
Nope, nothing. This is the strange thing. I would have assumed some message to appear at least.

**Comment by christianlupus** [comment]
The only thing I could try additionally is set `ALLOWED_HOSTS=*` and opening a connection directly to the nginx or django directly using SSH port forwarding.

**Comment by EliotBerriot** [comment]
Just to be sure, is the error happening on `/admin/` or `/accounts/login` ?

**Comment by christianlupus** [comment]
I did not try to connect to `/admin`. Just putting in the credentials and submitting opens `/accounts/login` with the error.

Update: When trying the admin console, I can log in.

**Comment by EliotBerriot** [comment]
Ok, if you can login to the admin, I think we can close the ticket, unless you have other configuration issues ?

I agree this is not ideal (and the other login page is confusing) but I really have no time to maintain Trax anymore these days :/

**Comment by christianlupus** [comment]
OK, now I see. I was mislead. I thought I needed to log into the main django application. Instead is was sufficient to log into the admin interface. I managed to configure trax with my mattermost installation now, I think successfully. Thank you very much.

**Comment by EliotBerriot** [comment]
Thank you!
